# Generated by Django 6.0.3 on 2026-03-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('MONOGRAFIA', 'Monografia'), ('RELATORIO_ESTAGIO', 'Relatório de Estágio'), ('RELATORIO_TECNICO', 'Relatório Técnico'), ('ARTIGO', 'Artigo')], max_length=20)),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês')], max_length=2)),
                ('semestre_letivo_defesa', models.CharField(blank=True, choices=[('2020/1', '2020/1'), ('2020/2', '2020/2'), ('2021/1', '2021/1'), ('2021/2', '2021/2'), ('2022/1', '2022/1'), ('2022/2', '2022/2'), ('2023/1', '2023/1'), ('2023/2', '2023/2'), ('2024/1', '2024/1'), ('2024/2', '2024/2'), ('2025/1', '2025/1'), ('2025/2', '2025/2'), ('2026/1', '2026/1')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('0', 'Em Elaboração'), ('1', 'Enviado'), ('2', 'Aprovado'), ('3', 'Reprovado')], default='0', max_length=1)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='tccs/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tccs', to='core.aluno')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tccs_coorientados', to='core.professor')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tccs_orientados', to='core.professor')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tccs_presididos', to='core.professor')),
                ('primeiro_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tccs_membro1', to='core.professor')),
                ('segundo_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tccs_membro2', to='core.professor')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidade_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.unidadeacademica'),
        ),
    ]
